server:
  port: 9090

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:h2:tcp://10.2.0.51:8082/~/lala;DB_CLOSE_DELAY=-1 #jdbc:h2:tcp://localhost/~/nodeDB #;MODE=LEGACY
=======
    url: jdbc:h2:tcp://10.2.0.51:9092/~/lala #;MODE=LEGACY
>>>>>>> 665b95cc65dd5a1bc37f3bc893dec1ea48e89cd5
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  path: /home/tobeornottobe/SSG_NodeManager/logs
  file: myapp.log
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
    org.springframework.transaction: DEBUG
